### ISSUE TITLE
Failed to build WAPITI gem native extension on linux

### ISSUE THREAD

**Issue by FerreroJeremy** [inukshuk/anystyle#142]
Hello, I'm just looking to install this project on my ubuntu env but I get this error :(

```
# gem install anystyle
Fetching: latex-decode-0.3.1.gem (100%)
Successfully installed latex-decode-0.3.1
Fetching: bibtex-ruby-5.1.4.gem (100%)
Successfully installed bibtex-ruby-5.1.4
Fetching: anystyle-data-1.2.0.gem (100%)
Successfully installed anystyle-data-1.2.0
Fetching: builder-3.2.4.gem (100%)
Successfully installed builder-3.2.4
Fetching: wapiti-1.0.7.gem (100%)
Building native extensions. This could take a while...
ERROR:  Error installing anystyle:
        ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.5.0/gems/wapiti-1.0.7/ext/wapiti
/usr/bin/ruby2.5 -r ./siteconf20200520-21321-daxumw.rb extconf.rb
checking for -lpthread... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/bin/$(RUBY_BASE_NAME)2.5
        --with-pthreadlib
        --without-pthreadlib
/usr/lib/ruby/2.5.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /usr/lib/ruby/2.5.0/mkmf.rb:541:in `try_link0'
        from /usr/lib/ruby/2.5.0/mkmf.rb:559:in `try_link'
        from /usr/lib/ruby/2.5.0/mkmf.rb:777:in `try_func'
        from /usr/lib/ruby/2.5.0/mkmf.rb:1004:in `block in have_library'
        from /usr/lib/ruby/2.5.0/mkmf.rb:947:in `block in checking_for'
        from /usr/lib/ruby/2.5.0/mkmf.rb:350:in `block (2 levels) in postpone'
        from /usr/lib/ruby/2.5.0/mkmf.rb:320:in `open'
        from /usr/lib/ruby/2.5.0/mkmf.rb:350:in `block in postpone'
        from /usr/lib/ruby/2.5.0/mkmf.rb:320:in `open'
        from /usr/lib/ruby/2.5.0/mkmf.rb:346:in `postpone'
        from /usr/lib/ruby/2.5.0/mkmf.rb:946:in `checking_for'
        from /usr/lib/ruby/2.5.0/mkmf.rb:999:in `have_library'
        from extconf.rb:20:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /var/lib/gems/2.5.0/extensions/x86_64-linux/2.5.0/wapiti-1.0.7/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.5.0/gems/wapiti-1.0.7 for inspection.
Results logged to /var/lib/gems/2.5.0/extensions/x86_64-linux/2.5.0/wapiti-1.0.7/gem_make.out
```

So I looked for some fixes on Google but nothing seemed to help.
I tried to install _ruby-dev_ instead _ruby-full_, I tried to update gem, I tried to install wapiti directly from git source, but nothing work :(

If anyone can help me... A big thank you!

**Comment by inukshuk** [comment]
Can you post the `mkmf.log` file? This should help clear things up; but most likely it will work if you `sudo apt install build-essential`.

**Comment by FerreroJeremy** [comment]
Thank for your answer.

I already test with build-essential installed, nothing change.

Below, the content of my _mkmf.log_ :

```
"gcc -o conftest -I/usr/include/x86_64-linux-gnu/ruby-2.5.0 -I/usr/include/ruby-2.5.0/ruby/backward -I/usr/include/ruby-2.5.0 -I. -Wdate-time -D_FORTIFY_SOURCE=2   -g -O2 -fdebug-prefix-map=/build/ruby2.5-B0MvC_/ruby2.5-2.5.1=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -std=gnu99 -W -Wall -Wno-declaration-after-statement -Werror=format-security -O3 conftest.c  -L. -L/usr/lib/x86_64-linux-gnu -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic     -lruby-2.5  -lpthread -lgmp -ldl -lcrypt -lm   -lc"
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */
```

**Comment by inukshuk** [comment]
Does it not include the actual error message?

If not you could try this yourself: create the test file with the contents above and try to compile it. I suspect you're missing some library.

For reference, you can also review the [build information here](https://travis-ci.org/github/inukshuk/wapiti-ruby/jobs/633925183) -- this is the log of compiling the Gem on trusty.
