### ISSUE TITLE
Error during custom training

### ISSUE THREAD

**Issue by dominic01** [inukshuk/anystyle#144]
I just added few references in the XML and tried the following.

```
$ anystyle train res/parser/core.xml sample.mod
Traceback (most recent call last):
        9: from /usr/local/rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
        8: from /usr/local/rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
        7: from /usr/local/rvm/gems/ruby-2.6.3/bin/anystyle:23:in `<main>'
        6: from /usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems.rb:304:in `activate_bin_path'
        5: from /usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems.rb:304:in `synchronize'
        4: from /usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems.rb:305:in `block in activate_bin_path'
        3: from /usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:1417:in `activate'
        2: from /usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:1435:in `activate_dependencies'
        1: from /usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:1435:in `each'
/usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:1443:in `block in activate_dependencies': **can't satisfy 'bibtex-ruby (~> 4.4)', already activated 'bibtex-ruby-5.1.4'** (Gem::LoadError)

$ gem list | grep bibtex
bibtex-ruby (5.1.4, 4.4.7)
```

Any pointers?

**Comment by dominic01** [comment]
Would like to close this request.
I was able to train via script
```
AnyStyle.parser.learn(..)
AnyStyle.parser.model.save(..)
```

**Comment by inukshuk** [comment]
You need to update the `anystyle-cli` gem to 1.3.1 (to go with 1.3.11 of the `anystyle` gem)

**Comment by dominic01** [comment]
This works after updating the anystyle-cli.
