### ISSUE TITLE
lib/anystyle/parser.rb:175:in `to_h': wrong number of arguments (given 1, expected 0) 

### ISSUE THREAD

**Issue by cboulanger** [inukshuk/anystyle#193]
Given the following code:

```ruby
pdf_paths.each do |path|
    file_path = File.join(Dir.pwd, path)
    file_id = File.basename(path, ".pdf")

    # find references
    doc =  AnyStyle.finder.find(file_path, format: :wapiti)[0]
    ref_lines = doc.to_s(tagged: false).gsub(/\u00AD ?/, "") # remove soft hyphen

    # label sequences and generate references
    sequences = AnyStyle.parser.label ref_lines
    refs = doc.references(normalize_blocks: false)
    puts " - #{file_id}: #{refs.length} references found"

    # translate to CSL
    dst = AnyStyle.parse(refs.join("\n"))
    csl = JSON.pretty_generate AnyStyle.parser.format_csl(dst)

```

I am getting the error 
```
.../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/anystyle-1.3.14/lib/anystyle/parser.rb:175:in `to_h': wrong number of arguments (given 1, expected 0) (
ArgumentError)
        from.../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/anystyle-1.3.14/lib/anystyle/parser.rb:175:in `block in format_hash'
        from .../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/anystyle-1.3.14/lib/anystyle/parser.rb:174:in `each'
        from .../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/anystyle-1.3.14/lib/anystyle/parser.rb:174:in `inject'
        from .../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/anystyle-1.3.14/lib/anystyle/parser.rb:174:in `format_hash'
        from .../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/anystyle-1.3.14/lib/anystyle/format/csl.rb:5:in `format_csl'
        from test/train-test-datasets.rb:109:in `block (2 levels) in <main>'
        from test/train-test-datasets.rb:94:in `each'
        from test/train-test-datasets.rb:94:in `block in <main>'
        from test/train-test-datasets.rb:90:in `each'
        from test/train-test-datasets.rb:90:in `<main>'
```

Is this a bug in my code, a version problem or an anystyle bug?

**Comment by cboulanger** [comment]
Ok it was my wrong usage of the API, correct one is:

```ruby
    # find references
    refs = AnyStyle.finder.find(file_path, format: :references)[0]
    ref_lines = refs.join("\n").gsub(/\u00AD ?/, "") # remove soft hyphen

    # label sequences and generate references
    seqs = AnyStyle.parser.label ref_lines

    # translate to CSL
    csl = JSON.pretty_generate AnyStyle.parser.format_csl(seqs)
```

but now I am back at getting segmentation faults, continuing in the other issue.

**Comment by cboulanger** [comment]
One thing I had trouble finding out is what type of value the different API calls return - some documentation on this would be highly welcome!
