### ISSUE TITLE
anystyle find: File name too long @ rb_sysopen

### ISSUE THREAD

**Issue by tylerandrewscott** [inukshuk/anystyle#205]
I am encountering an issue I have not previously experienced using anystyle find. What appears to be happening is the program tries to use the text of the file as the output file name, but I'm unsure why it would do so. Here's an example, using a pdf that someone else has already successfully used in a prior issue (https://github.com/inukshuk/anystyle/issues/184).  Happy to provide any other info that could be helpful in resolving.

```
> wget https://iase-web.org/documents/papers/icots5/Topic1m.pdf
> anystyle -f csl find Topic1m.pdf         
Error processing `Topic1m.pdf'
  File name too long @ rb_sysopen - results as if they had the status of mathematical theorems or of physical laws (Rogerson, 1990). At school level in the UK this approach to statistics teaching originated during the early developmental period of the School Mathematics Project (1960-1975), and has since influenced many projects, especially the Mathematics in Society Project (1980-) whose materials are now widely used (Rogerson, 1986).
Kuhn, T. (1972). The Structure of Scientific Revolutions. Phoenix.
Lakatos, I. (1976). Proofs and Refutations, Cambridge, CUP.
Money, R., and Sentry, K. (1990). Common assessment tasks in VCE mathematics. In: Mathematical Turning Points, Proc. 13th Biennial Conference of the Australian Association of Mathematics Teachers, Hobart, Tasmania.
Rogerson, A. (1986).The mathematics in society project: a new conception of mathematics, Int. J. Math. Educ. Sci. Technol. 17(5).
Rogerson, A. (1987). How should we teach probability and statistics, in From Now to The Future, Melbourne, MAV.
Rogerson, A. (1989). Mathematics, society and culture - the major theme for the 1990’s. In B. Doig (Ed.) Mathematics Counts, Melbourne, MAV.
Rogerson, A. (1990). Integrated real life themes and the teaching of probability & statistics at 11-16 Level. The Proceedings of the ICOTS 3 Conference, Dunedin, New Zealand.
  /Users/tscott/.gem/ruby/3.2.0/gems/wapiti-2.1.0/lib/wapiti/dataset.rb:42:in `read'
  /Users/tscott/.gem/ruby/3.2.0/gems/wapiti-2.1.0/lib/wapiti/dataset.rb:42:in `open'
```

**Comment by inukshuk** [comment]
Sorry about that! Should be fixed if you update `anystyle-cli` to version 1.4.2.
